name: common
'on':
  push:
    paths:
    - common/**
    - '*.kts'
    - .monopolis/config.yml
    - .github/workflows/common-build.yml
jobs:
  Build:
    needs: [
      ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - run: ./gradlew :common:check
    runs-on: ubuntu-latest
