name: entry-logger
'on':
  push:
    paths:
    - entry-logger/**
    - common/**
    - .monopolis/config.yml
    - .github/workflows/app1-build.yml
jobs:
  Build:
    needs: [
      ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew :entry-logger:check
    runs-on: ubuntu-latest
