name: entry-logger-deploy
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy entry-logger to.
        required: true
        type: environment
      entry-logger:
        description: Version of entry-logger to deploy.
        required: true
        type: string
      deployment_id:
        description: GitHub Deployment id.
        required: false
        type: string
jobs:
  Start:
    name: Start ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.deployment_id != null }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: [
      ]
    outputs:
      shas: ${{ steps.start_monode_deployment.outputs.environment_map }}
    steps:
    - uses: monopolis-cloud/start-monode-deployment@v2
      id: start_monode_deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Deploy-entry_logger:
    name: Deploy ${{ github.event.inputs.entry-logger }}
    if: ${{ always()  }}
    runs-on: ubuntu-latest
    needs:
    - Start
    steps:
    - run: echo deploy entry-logger here
  End:
    name: End ${{ github.event.inputs.environment }}
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
    - Deploy-entry_logger
    steps:
    - uses: monopolis-cloud/finish-monode-deployment@v2
      with:
        status: ${{ needs.Deploy-entry_logger.result }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
