name: user-directory-deploy
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy user-directory to.
        required: true
        type: environment
      user-directory:
        description: Version of user-directory to deploy.
        required: true
        type: string
      deployment_id:
        description: GitHub Deployment id.
        required: false
        type: string
jobs:
  Start:
    name: Start ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: [
      ]
    outputs:
      shas: ${{ steps.start_monode_deployment.outputs.environment_map }}
    steps:
    - uses: monopolis-cloud/start-monode-deployment@v2
      id: start_monode_deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Deploy-user-directory:
    needs:
    - Start
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: monopolis-user-directory
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        procfile: 'web: user-directory/build/install/user-directory/bin/user-directory
          $PORT'
    runs-on: ubuntu-latest
    if: ${{ always()  }}
  End:
    name: End ${{ github.event.inputs.environment }}
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
    - Deploy-user-directory
    steps:
    - uses: monopolis-cloud/finish-monode-deployment@v2
      with:
        status: ${{ needs.Deploy-user-directory.result }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
