name: user-directory-deploy
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy user-directory to.
        required: true
        type: environment
      user-directory:
        description: Version of user-directory to deploy.
        required: true
        type: string
      deployment_id:
        description: GitHub Deployment id.
        required: false
        type: string
jobs:
  Start:
    name: Start ${{ github.event.inputs.environment }}
    if: ${{ github.event.inputs.deployment_id != null }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: [
      ]
    outputs:
      shas: ${{ steps.start_monode_deployment.outputs.environment_map }}
    steps:
    - uses: monopolis-cloud/start-monode-deployment@v2
      id: start_monode_deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Deploy-user_directory:
    name: Deploy ${{ github.event.inputs.user-directory }}
    if: ${{ always()  }}
    runs-on: ubuntu-latest
    needs:
    - Start
    steps:
    - run: echo deploy user-directory here
  End:
    name: End ${{ github.event.inputs.environment }}
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
    - Deploy-user_directory
    steps:
    - uses: monopolis-cloud/finish-monode-deployment@v2
      with:
        status: ${{ needs.Deploy-user_directory.result }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
